version: "3.3"

services:
  postgres:
    container_name: kurse_postgres_container
    image: postgres:13-alpine
    ports:
      - "9000:5432"
    env_file:
      - ./environment
    volumes:
      - "./database.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - "./db/postgres:/var/lib/postgresql/data"
    networks:
      - postgres

  api:
    container_name: kurse_api
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    env_file:
      - ./environment
    ports:
      - 9001:8000
    networks:
      - postgres

networks:
  postgres:
    driver: bridge