version: "3.3"

services:
  postgres:
    container_name: kurse_postgres_container
    image: postgres:13-alpine
    ports:
      - "9000:5432"
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=masterPassword
      - POSTGRES_DB=hostel
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./database.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - "./db/postgres:/var/lib/postgresql/data"
    networks:
      - postgres

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 9001:8000
networks:
  postgres:
    driver: bridge